# Generated by Django 6.0.6 on 2026-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='garantia',
            field=models.CharField(default='30 Días', max_length=40),
        ),
    ]
