# Generated by Django 6.0.6 on 2026-09-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0007_alter_historialsolicitud_accion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_dias', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('condiciones_publicas', models.TextField(blank=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('creada_por_username', models.CharField(blank=True, max_length=150)),
                ('creada_por_nombre', models.CharField(blank=True, max_length=150)),
                ('creada_por_rol', models.CharField(blank=True, max_length=20)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('anulada_por_username', models.CharField(blank=True, max_length=150)),
                ('anulada_por_nombre', models.CharField(blank=True, max_length=150)),
                ('anulada_por_rol', models.CharField(blank=True, max_length=20)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_anuladas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_creadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud_original', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='garantia', to='servicios.solicitudservicio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReingresoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('observaciones_internas', models.TextField(blank=True)),
                ('registrado_por_username', models.CharField(blank=True, max_length=150)),
                ('registrado_por_nombre', models.CharField(blank=True, max_length=150)),
                ('registrado_por_rol', models.CharField(blank=True, max_length=20)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('garantia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reingreso', to='garantias.garantia')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reingresos_garantia_registrados', to=settings.AUTH_USER_MODEL)),
                ('solicitud_reingreso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reingreso_garantia', to='servicios.solicitudservicio')),
            ],
            options={
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['fecha_vencimiento'], name='garantia_vence_idx'),
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['anulada_en'], name='garantia_anulada_idx'),
        ),
        migrations.AddConstraint(
            model_name='garantia',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_dias__gt', 0)), name='garantia_duracion_positiva'),
        ),
        migrations.AddConstraint(
            model_name='garantia',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gte', models.F('fecha_inicio'))), name='garantia_fechas_validas'),
        ),
    ]
