# Generated by Django 6.0.6 on 2026-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=140)),
                ('categoria', models.CharField(choices=[('Almacenamiento', 'Almacenamiento'), ('Pantallas', 'Pantallas'), ('Baterias', 'Baterias'), ('Accesorios', 'Accesorios'), ('Cables', 'Cables'), ('Otros', 'Otros')], max_length=40)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ubicacion', models.CharField(max_length=120)),
                ('nota', models.CharField(blank=True, max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
