# Generated by Django 6.0.6 on 2026-07-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
        ('servicios', '0004_replace_cliente_presencial_with_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='servicios.solicitudservicio'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('registro', 'Registro'), ('ajuste', 'Ajuste'), ('salida', 'Salida por reparación')], max_length=20),
        ),
    ]
