# Generated by Django 6.0.6 on 2026-07-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='tecnicos.tecnico'),
        ),
    ]
