# Generated by Django 6.0.6 on 2026-09-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_structured_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('asignacion', 'Asignación'), ('inicio', 'Inicio'), ('cambio_estado', 'Cambio de estado'), ('diagnostico', 'Diagnóstico'), ('finalizacion', 'Finalización'), ('cancelacion', 'Cancelación'), ('garantia_activada', 'Garantía activada'), ('garantia_utilizada', 'Garantía utilizada'), ('garantia_anulada', 'Garantía anulada')], max_length=30),
        ),
    ]
