# Generated by Django 6.0.6 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0007_alter_historialsolicitud_accion"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="solicitudservicio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    estado__in=[
                        "pendiente",
                        "en_proceso",
                        "completado",
                        "cancelado",
                    ]
                ),
                name="servicio_estado_valido",
            ),
        ),
    ]
