# Generated by Django 6.0.6 on 2026-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='TecniTrack Services', max_length=120)),
                ('correo', models.EmailField(default='soporte@tecnitrack.com', max_length=254)),
                ('direccion', models.CharField(default='Managua', max_length=180)),
                ('telefono', models.CharField(default='8888-0000', max_length=25)),
                ('whatsapp', models.CharField(default='8888-0000', max_length=25)),
                ('horario', models.CharField(default='Lun-Sab', max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del taller',
                'verbose_name_plural': 'Configuracion del taller',
            },
        ),
    ]
